version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: commitizen
    versions:
    - "< 3.0.5, >= 3.0.4.a"
  - dependency-name: "@vercel/ncc"
    versions:
    - 0.28.1
  - dependency-name: ts-jest
    versions:
    - 26.5.3
  - dependency-name: husky
    versions:
    - 5.0.9
  - dependency-name: semantic-release
    versions:
    - 17.3.8
