# These are supported funding model platforms

github: KengoTODA # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: KengoTODA  Replace with a single Patreon username
issuehunt: kengotoda # Replace with a single IssueHunt username
