dist: xenial
language: node_js
cache:
  directories:
    - ~/.npm
script:
    - yarn
    - yarn build
    - yarn test
after_success:
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
