dist: xenial
language: node_js
cache:
  directories:
    - ~/.npm
before_install:
  - npm install -g yarn
install:
  - yarn
script:
  - yarn build
  - yarn test
after_success:
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
