name: Integration Test
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  staging:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to the staging site
        uses: ./
        with:
          github-token: ${{ secrets.PAT }}
          rtd-token: ${{ secrets.RTD_TOKEN }}
          rtd-project: your-read-the-docs-project
