name: Test with tokens

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  jest:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: npm
      - name: Build
        run: |
          npm ci
          npm test
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          RTD_TOKEN: ${{ secrets.RTD_TOKEN }}
      - uses: LouisBrunner/checks-action@v1.1.2
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: test-with-tokens
          sha: ${{ github.event.workflow_run.head_sha }}
          conclusion: ${{ job.status }}
          details_url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
