name: Test with tokens

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  jest:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: npm
      - name: Build
        run: |
          npm ci
          npm test
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          RTD_TOKEN: ${{ secrets.RTD_TOKEN }}
